services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: smart_park_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data